project:
  type: website
  output-dir: _site
  preview:
    port: 6925

extensions:
  iconify:
    style: "color: #b22222;"

website:
  site-url: "http://localhost:6925"
  sidebar:
    style: docked
    title: "STAT 206"
    logo: assets/UC_Riverside_Horiz_WhtBG.png
    logo-alt: "UC Riverside monogram logo"
    collapse-level: 1
    contents:
      - text: Home
        href: index.qmd
      - text: Office Hours
        href: office_hours.qmd
      - text: Schedule
        href: schedule.qmd
      - text: "---"
      - section: Module 1 (Fundamentals)
        contents:
          - text: The Unix Shell
            href: notes/module01/unix.qmd
          - text: The File System
            href: notes/module01/filesystem.qmd
          - text: Quarto
            href: notes/module01/quarto.qmd
          - text: Git
            href: notes/module01/git.qmd
      - section: Module 2 (Programming)
        contents:
          - text: Types
          - text: Basic Operations
          - text: Control Flow
            # href: notes/module02/control.qmd
          - text: Functions
            # href: notes/module02/functions.qmd
          - text: Multiple Dispatch
      - section: Module 3 (Best Practices)
        contents:
          - text: Package Management
          - text: Error Handling
          - text: Debugging
          - text: Defensive Programming
          - text: Testing
          - text: Refactoring
            # href: notes/module03/refactoring.qmd
      - section: Module 4 (Numerical Basics)
        contents:
          - text: Computer Arithmetic
            # href: notes/module04/numbers.qmd
          - text: Computer Architecture
            # href: notes/module04/computers.qmd
          - text: Algorithms Introduction
            # href: notes/module04/algorithms.qmd
          - text: Linear Algebra Introduction
            # href: notes/module04/linalg.qmd
          - text: BLAS/LAPACK
            # href: notes/module04/blas.qmd
      - section: Module 5 (Linear Systems)
        contents:
          - text: Easy Systems
          - text: Condition Numbers
          - text: QR 
          - text: Cholesky
          - text: Eigen
          - text: SVD
          - text: Iterative Methods
      - section: Module 6 (Simulation)
        contents:
          - text: RNG and PRNGs
          - text: Inverse Method
          - text: Rejection Sampling
          - text: Monte Carlo Methods
          - text: Distributions.jl
      - section: Module 7 (Resampling)
        contents:
          - text: Bootstrap
          - text: Permutation
          - text: Cross Validation
      - section: Module 8 (Optimization)
        contents:
          - text: First-Order Methods
          - text: Second-Order Methods
          - text: Zero-Order Methods
          - text: Automatic Differentiation
      - section: Module 9 (Data Technologies)
        contents:
          - text: Plaintext and Binary Formats
          - text: Tabular Data
          - text: DataFrames.jl
          - text: Databases and SQL
          - text: DuckDB and DuckDB.jl
      - text: "---"
      - section: "Labs"
        contents:
          - text: Lab 0 (Getting Started)
            href: labs/lab0-setup.qmd
          # - text: Lab 1 (Submitting Assignments)
          #   href: labs/lab1-submit.qmd
          # - text: Lab 2 (Errors and Debugging)
          #   href: labs/lab2-debug.qmd
          # - text: Lab 3 (I/O Handling)
          #   href: labs/lab3-io.qmd
          # - text: Lab 4 (Reproducibility)
          #   href: labs/lab4-reproducibility.qmd
          # - text: Lab 5 (Code Review)
          #   href: labs/lab5-codereview.qmd
          # - text: Lab 6 (TBD)
          #   href: labs/lab6-tbd.qmd
          # - text: Lab 7 (Simulation)
          #   href: labs/lab7-simulation.qmd
          # - text: Lab 8 (Collaboration using Git)
          #   href: labs/lab8-collab.qmd
      - section: "Homework"
        contents:
          - text: Homework 1
            # href: hw/hw1.qmd
          # - text: Homework 2
          #   href: hw/hw2.qmd
          # - text: Homework 3
          #   href: hw/hw3.qmd
          # - text: Homework 4
          #   href: hw/hw4.qmd
          # - text: Homework 5
          #   href: hw/hw5.qmd
          # - text: Homework 6
          #   href: hw/hw6.qmd
          # - text: Homework 7
          #   href: hw/hw7.qmd
          # - text: Homework 8
          #   href: hw/hw8.qmd
      - text: "Final Project"
        href: project/project.qmd
      - text: "---"
      - section: "How to..."
        contents:
          - text: Use Docker
            href: howto/use_docker.qmd
          - text: Use VSCode with a Container
            href: howto/use_vscode.qmd
          - text: Submit Assignments
            href: howto/submit_hw.qmd
          # - text: Use Julia Environments
          #   href: howto/use_pkg.qmd
          - text: Use Revise.jl
            href: howto/use_revise.qmd
          # - text: Plot in Julia
          #   href: howto/use_plots.qmd
            

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    code-line-numbers: true
    grid:
      sidebar-width: 350px

execute:
  engine: markdown
  freeze: auto